package makefile

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/snowmerak/aloy/internal/cmake"
	"github.com/snowmerak/aloy/internal/model"
	"github.com/snowmerak/aloy/internal/parser"
	"github.com/snowmerak/aloy/internal/resolver"
)

func GenerateMaster(projectRoot string, cfg *model.ProjectConfig, resolvedDeps []resolver.ResolvedDep) error {
	var b strings.Builder

	fmt.Fprintf(&b, "# Auto-generated by aloy — DO NOT EDIT\n")
	fmt.Fprintf(&b, "CXX ?= g++\n")
	fmt.Fprintf(&b, "AR ?= ar\n")
	if cfg.Project.CXXStandard > 0 {
		fmt.Fprintf(&b, "CXXFLAGS ?= -std=c++%d\n", cfg.Project.CXXStandard)
	} else {
		fmt.Fprintf(&b, "CXXFLAGS ?=\n")
	}
	fmt.Fprintf(&b, "LDFLAGS ?=\n")
	fmt.Fprintf(&b, "MODULES_DIR := %s\n", resolver.ModulesDir)
	fmt.Fprintf(&b, "\n")

	depDirs := uniqueGitDepDirs(cfg, resolvedDeps)
	if len(depDirs) > 0 {
		fmt.Fprintf(&b, ".PHONY: deps")
		for _, d := range depDirs {
			fmt.Fprintf(&b, " dep-%s", sanitize(d))
		}
		fmt.Fprintf(&b, "\n")
		fmt.Fprintf(&b, "deps:")
		for _, d := range depDirs {
			fmt.Fprintf(&b, " dep-%s", sanitize(d))
		}
		fmt.Fprintf(&b, "\n\n")
		for _, d := range depDirs {
			fmt.Fprintf(&b, ".PHONY: dep-%s\n", sanitize(d))
			fmt.Fprintf(&b, "dep-%s:\n", sanitize(d))
			fmt.Fprintf(&b, "\t$(MAKE) -C $(MODULES_DIR)/%s\n\n", d)
		}
	} else {
		fmt.Fprintf(&b, ".PHONY: deps\n")
		fmt.Fprintf(&b, "deps:\n\n")
	}

	targetNames := make([]string, 0, len(cfg.Targets))
	for name := range cfg.Targets {
		targetNames = append(targetNames, name)
	}
	sort.Strings(targetNames)

	allTargets := make([]string, 0, len(targetNames))
	for _, name := range targetNames {
		t := cfg.Targets[name]
		n := sanitize(name)
		if t.Type == "header_only" {
			continue
		}
		allTargets = append(allTargets, n)
	}

	fmt.Fprintf(&b, ".PHONY: all clean")
	for _, n := range allTargets {
		fmt.Fprintf(&b, " %s", n)
	}
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "all: deps")
	for _, n := range allTargets {
		fmt.Fprintf(&b, " %s", n)
	}
	fmt.Fprintf(&b, "\n\n")

	for _, name := range targetNames {
		t := cfg.Targets[name]
		if t.Type == "header_only" {
			continue
		}
		out := sanitize(name)
		sources, err := cmake.ScanSources(t.Sources, projectRoot)
		if err != nil {
			return fmt.Errorf("failed to scan sources for target %s: %w", name, err)
		}
		if len(sources) == 0 {
			continue
		}

		objs := make([]string, 0, len(sources))
		for _, s := range sources {
			objs = append(objs, objName(out, s))
		}

		for _, s := range sources {
			obj := objName(out, s)
			fmt.Fprintf(&b, "%s: %s\n", obj, s)
			fmt.Fprintf(&b, "\t@mkdir -p $(dir $@)\n")
			fmt.Fprintf(&b, "\t$(CXX) $(CXXFLAGS)%s -c $< -o $@\n\n", includeFlags(&t))
		}

		fmt.Fprintf(&b, "%s: %s\n", out, strings.Join(objs, " "))
		switch t.Type {
		case "library":
			fmt.Fprintf(&b, "\t$(AR) rcs $@ %s\n\n", strings.Join(objs, " "))
		case "shared_library":
			fmt.Fprintf(&b, "\t$(CXX) -shared -o $@ %s $(LDFLAGS)\n\n", strings.Join(objs, " "))
		default:
			fmt.Fprintf(&b, "\t$(CXX) -o $@ %s $(LDFLAGS)\n\n", strings.Join(objs, " "))
		}
	}

	fmt.Fprintf(&b, "clean:\n")
	fmt.Fprintf(&b, "\trm -rf .aloy_make_objs")
	for _, n := range allTargets {
		fmt.Fprintf(&b, " %s", n)
	}
	fmt.Fprintf(&b, "\n")

	return os.WriteFile(filepath.Join(projectRoot, "Makefile"), []byte(b.String()), 0644)
}

func GenerateForModule(modulePath string) error {
	cfg, err := parser.LoadProject(modulePath)
	if err != nil {
		return fmt.Errorf("failed to load module project.yaml: %w", err)
	}
	return GenerateMaster(modulePath, cfg, nil)
}

func uniqueGitDepDirs(cfg *model.ProjectConfig, resolved []resolver.ResolvedDep) []string {
	resolvedSet := make(map[string]bool)
	for _, r := range resolved {
		if !r.IsSystem {
			resolvedSet[r.ModuleDir] = true
		}
	}
	seen := make(map[string]bool)
	var result []string
	for _, t := range cfg.Targets {
		for _, d := range t.Dependencies {
			if d.Type == "system" {
				continue
			}
			dir := d.ModuleDir()
			if !resolvedSet[dir] || seen[dir] {
				continue
			}
			seen[dir] = true
			result = append(result, dir)
		}
	}
	sort.Strings(result)
	return result
}

func sanitize(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' || r == '.' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	if b.Len() == 0 {
		return "unnamed"
	}
	return b.String()
}

func includeFlags(t *model.Target) string {
	var parts []string
	for _, inc := range t.Includes.Public {
		parts = append(parts, " -I"+inc)
	}
	for _, inc := range t.Includes.Private {
		parts = append(parts, " -I"+inc)
	}
	return strings.Join(parts, "")
}

func objName(targetName, src string) string {
	clean := strings.ReplaceAll(src, "/", "_")
	return filepath.ToSlash(filepath.Join(".aloy_make_objs", targetName, clean+".o"))
}
