project:
    name: example
    version: 0.1.0
    cxx_standard: 17
targets:
    example:
        type: executable
        sources:
            - src/**/*.cpp
        includes:
            public:
                - include/
        dependencies:
            - name: fmt
              git: https://github.com/fmtlib/fmt
              version: '>=9.0.0'
            - name: json
              git: https://github.com/nlohmann/json
              version: '>=3.11.0'
              cmake_target: nlohmann_json
            - name: testlib
              git: C:/Users/snowm/Projects/snowmerak/aloy/testlib
              version: ^1.0.0
