package cmake

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/snowmerak/aloy/internal/model"
	"github.com/snowmerak/aloy/internal/parser"
	"github.com/snowmerak/aloy/internal/resolver"
)

// GenerateMaster creates the root CMakeLists.txt for the project.
func GenerateMaster(projectRoot string, cfg *model.ProjectConfig, resolvedDeps []resolver.ResolvedDep) error {
	var b strings.Builder

	writeHeader(&b, cfg)
	writeDependencies(&b, cfg, resolvedDeps)
	if err := writeTargets(&b, cfg, projectRoot); err != nil {
		return err
	}
	writeInjectCMake(&b, cfg)

	path := filepath.Join(projectRoot, "CMakeLists.txt")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

// GenerateForModule creates a CMakeLists.txt for an aloy sub-package in .my_modules/.
func GenerateForModule(modulePath string) error {
	cfg, err := parser.LoadProject(modulePath)
	if err != nil {
		return fmt.Errorf("failed to load module project.yaml: %w", err)
	}

	var b strings.Builder

	fmt.Fprintf(&b, "# Auto-generated by aloy — DO NOT EDIT\n")
	fmt.Fprintf(&b, "cmake_minimum_required(VERSION 3.15)\n")
	fmt.Fprintf(&b, "project(%s)\n\n", sanitizeCMakeName(cfg.Project.Name))

	if cfg.Project.CXXStandard > 0 {
		fmt.Fprintf(&b, "set(CMAKE_CXX_STANDARD %d)\n", cfg.Project.CXXStandard)
		b.WriteString("set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n")
	}

	// Write targets for this module
	for targetName, target := range cfg.Targets {
		cmakeName := sanitizeCMakeName(targetName)
		sources, err := ScanSources(target.Sources, modulePath)
		if err != nil {
			return fmt.Errorf("failed to scan sources for target %s: %w", targetName, err)
		}
		if err := writeTargetBlock(&b, cmakeName, &target, sources, modulePath); err != nil {
			return fmt.Errorf("failed to write target %s: %w", targetName, err)
		}
	}

	path := filepath.Join(modulePath, "CMakeLists.txt")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

func writeHeader(b *strings.Builder, cfg *model.ProjectConfig) {
	fmt.Fprintf(b, "# Auto-generated by aloy — DO NOT EDIT\n")
	fmt.Fprintf(b, "cmake_minimum_required(VERSION 3.15)\n")
	fmt.Fprintf(b, "project(%s VERSION %s)\n\n",
		sanitizeCMakeName(cfg.Project.Name), cfg.Project.Version)

	if cfg.Project.CXXStandard > 0 {
		fmt.Fprintf(b, "set(CMAKE_CXX_STANDARD %d)\n", cfg.Project.CXXStandard)
		b.WriteString("set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n")
	}
}

func writeDependencies(b *strings.Builder, cfg *model.ProjectConfig, resolvedDeps []resolver.ResolvedDep) {
	// Build a lookup for resolved deps
	depMap := make(map[string]*resolver.ResolvedDep)
	for i := range resolvedDeps {
		depMap[resolvedDeps[i].ModuleDir] = &resolvedDeps[i]
	}

	// Collect all unique dependencies across targets
	seen := make(map[string]bool)
	var allDeps []model.Dependency
	for _, target := range cfg.Targets {
		for _, dep := range target.Dependencies {
			key := dep.ModuleDir()
			if !seen[key] {
				seen[key] = true
				allDeps = append(allDeps, dep)
			}
		}
	}

	// System packages: find_package
	for _, dep := range allDeps {
		if dep.Type == "system" {
			fmt.Fprintf(b, "find_package(%s REQUIRED)\n", dep.Name)
		}
	}

	// Git packages: cmake_options + add_subdirectory
	for _, dep := range allDeps {
		if dep.Type == "system" {
			continue
		}
		dirName := dep.ModuleDir()
		rd := depMap[dirName]
		if rd == nil {
			continue
		}

		// Inject cmake_options as cache variables
		for k, v := range dep.CMakeOptions {
			cacheType := "STRING"
			upper := strings.ToUpper(v)
			if upper == "ON" || upper == "OFF" || upper == "TRUE" || upper == "FALSE" {
				cacheType = "BOOL"
			}
			fmt.Fprintf(b, "set(%s %q CACHE %s \"\" FORCE)\n", k, v, cacheType)
		}

		fmt.Fprintf(b, "add_subdirectory(%s/%s)\n", resolver.ModulesDir, dirName)
	}

	if len(allDeps) > 0 {
		b.WriteString("\n")
	}
}

func writeTargets(b *strings.Builder, cfg *model.ProjectConfig, projectRoot string) error {
	for targetName, target := range cfg.Targets {
		cmakeName := sanitizeCMakeName(targetName)

		// Scan source files (hardcoded, no GLOB)
		sources, err := ScanSources(target.Sources, projectRoot)
		if err != nil {
			return fmt.Errorf("failed to scan sources for target %s: %w", targetName, err)
		}

		if err := writeTargetBlock(b, cmakeName, &target, sources, projectRoot); err != nil {
			return fmt.Errorf("failed to write target %s: %w", targetName, err)
		}
		b.WriteString("\n")
	}
	return nil
}

func writeTargetBlock(b *strings.Builder, cmakeName string, target *model.Target, sources []string, projectRoot string) error {
	// Add target
	switch target.Type {
	case "executable":
		fmt.Fprintf(b, "add_executable(%s)\n", cmakeName)
	case "library":
		fmt.Fprintf(b, "add_library(%s STATIC)\n", cmakeName)
	case "shared_library":
		fmt.Fprintf(b, "add_library(%s SHARED)\n", cmakeName)
	case "header_only":
		fmt.Fprintf(b, "add_library(%s INTERFACE)\n", cmakeName)
	default:
		fmt.Fprintf(b, "add_executable(%s)\n", cmakeName)
	}

	// Sources (not for header_only)
	if target.Type != "header_only" && len(sources) > 0 {
		fmt.Fprintf(b, "target_sources(%s PRIVATE\n", cmakeName)
		for _, s := range sources {
			fmt.Fprintf(b, "    %s\n", s)
		}
		b.WriteString(")\n")
	}

	// Include directories
	if len(target.Includes.Public) > 0 {
		keyword := "PUBLIC"
		if target.Type == "header_only" {
			keyword = "INTERFACE"
		}
		fmt.Fprintf(b, "target_include_directories(%s %s\n", cmakeName, keyword)
		for _, inc := range target.Includes.Public {
			fmt.Fprintf(b, "    %s\n", inc)
		}
		b.WriteString(")\n")
	}
	if len(target.Includes.Private) > 0 && target.Type != "header_only" {
		fmt.Fprintf(b, "target_include_directories(%s PRIVATE\n", cmakeName)
		for _, inc := range target.Includes.Private {
			fmt.Fprintf(b, "    %s\n", inc)
		}
		b.WriteString(")\n")
	}

	// Link dependencies
	if len(target.Dependencies) > 0 {
		keyword := "PRIVATE"
		if target.Type == "header_only" {
			keyword = "INTERFACE"
		}
		fmt.Fprintf(b, "target_link_libraries(%s %s\n", cmakeName, keyword)
		for _, dep := range target.Dependencies {
			var linkName string
			if dep.Type == "system" {
				linkName = dep.Name
			} else if dep.CMakeTarget != "" {
				linkName = dep.CMakeTarget
			} else {
				linkName = dep.TargetName()
			}
			fmt.Fprintf(b, "    %s\n", linkName)
		}
		b.WriteString(")\n")
	}

	// Platform-specific blocks
	for platform, pcfg := range target.Platforms {
		cond := platformCondition(platform)
		if cond == "" {
			continue
		}

		fmt.Fprintf(b, "if(%s)\n", cond)

		if len(pcfg.Sources) > 0 && target.Type != "header_only" {
			platSources, err := ScanSources(pcfg.Sources, projectRoot)
			if err != nil {
				return fmt.Errorf("failed to scan platform %s sources: %w", platform, err)
			}
			fmt.Fprintf(b, "    target_sources(%s PRIVATE\n", cmakeName)
			for _, s := range platSources {
				fmt.Fprintf(b, "        %s\n", s)
			}
			b.WriteString("    )\n")
		}

		if len(pcfg.CompilerFlags) > 0 {
			keyword := "PRIVATE"
			if target.Type == "header_only" {
				keyword = "INTERFACE"
			}
			fmt.Fprintf(b, "    target_compile_options(%s %s %s)\n",
				cmakeName, keyword, strings.Join(pcfg.CompilerFlags, " "))
		}

		if len(pcfg.LinkerFlags) > 0 && target.Type != "header_only" {
			fmt.Fprintf(b, "    target_link_options(%s PRIVATE %s)\n",
				cmakeName, strings.Join(pcfg.LinkerFlags, " "))
		}

		b.WriteString("endif()\n")
	}
	return nil
}

func writeInjectCMake(b *strings.Builder, cfg *model.ProjectConfig) {
	if cfg.InjectCMake != "" {
		fmt.Fprintf(b, "\ninclude(%s)\n", cfg.InjectCMake)
	}
}

func platformCondition(name string) string {
	switch strings.ToLower(name) {
	case "windows", "win", "win32":
		return "WIN32"
	case "linux":
		return "UNIX AND NOT APPLE"
	case "macos", "macosx", "darwin", "apple":
		return "APPLE"
	case "unix":
		return "UNIX"
	default:
		return ""
	}
}

func sanitizeCMakeName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	s := b.String()
	if s == "" {
		return "unnamed"
	}
	// CMake names cannot start with a digit
	if s[0] >= '0' && s[0] <= '9' {
		s = "_" + s
	}
	return s
}
